/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _YTF_FUNCTIONS_FUNCTIONS_H_
#define _YTF_FUNCTIONS_FUNCTIONS_H_

/* declared in ./flat_parse.c */
extern
void flat_parse
  (gpeg_capture_t* c, ytf_array_t* array);

/* declared in ./json_parse.c */
extern
ytf_t* json_parse
  (gpeg_capture_t* c)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_encode.c */
extern
void ytf_encode_bit
  (ytf_parse_t* ytf, unsigned bit);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_bit
  (ytf_parse_t* ytf, unsigned* bit);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_bits
  (ytf_parse_t* ytf, unsigned bits, unsigned nbits);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_bits
  (ytf_parse_t* ytf, unsigned* bits, unsigned nbits);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_type
  (ytf_parse_t* ytf, unsigned type);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_type
  (ytf_parse_t* ytf, unsigned* type);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_byte
  (ytf_parse_t* ytf, unsigned char B);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_byte
  (ytf_parse_t* ytf, unsigned char* B);

/* declared in ./ytf_encode_buffer.c */
extern
void ytf_encode_buffer
  (ytf_parse_t* ytf, unsigned char* buf, unsigned size);

/* declared in ./ytf_encode_buffer.c */
extern
void ytf_decode_buffer
  (ytf_parse_t* ytf, vec_t* vec);

/* declared in ./ytf_encode_float.c */
extern
void ytf_encode_float
  (ytf_parse_t* ytf, double d);

/* declared in ./ytf_encode_float.c */
extern
void ytf_decode_float
  (ytf_parse_t* ytf, double* d);

/* declared in ./ytf_encode_int.c */
extern
void ytf_encode_int
  (ytf_parse_t* ytf, int64_t n);

/* declared in ./ytf_encode_int.c */
extern
void ytf_decode_int
  (ytf_parse_t* ytf, int64_t* n);

/* declared in ./ytf_encode_lv.c */
extern
void ytf_encode_lv
  (ytf_parse_t* ytf, void* buf, unsigned size);

/* declared in ./ytf_encode_lv.c */
extern
void ytf_decode_lv
  (ytf_parse_t* ytf, void* buf, unsigned size);

/* declared in ./ytf_format_bin.c */
extern
void ytf_format_bin_continuous
  (ytf_t* ytf, ytf_parse_t* state);

/* declared in ./ytf_format_bin.c */
extern
void ytf_format_bin
  (ytf_t* ytf, vec_t* bin);

/* declared in ./ytf_format_flat.c */
extern
void ytf_format_flat_tagged
  (ytf_t* ytf, vec_t* flat, char* tag);

/* declared in ./ytf_format_flat.c */
extern
void ytf_format_flat
  (ytf_t* ytf, vec_t* flat);

/* declared in ./ytf_format_json.c */
extern
void ytf_format_json_string
  (unsigned char* str, unsigned size, vec_t* json);

/* declared in ./ytf_format_json.c */
extern
void ytf_format_json
  (ytf_t* ytf, vec_t* json);

/* declared in ./ytf_free.c */
extern
void ytf_free
  (ytf_t* ytf);

/* declared in ./ytf_parse_bin.c */
extern
void ytf_parse_bin
  (const vec_t* string, ytf_t* ytf);

/* declared in ./ytf_parse_flat.c */
extern
int ytf_parse_flat
  (const vec_t* string, ytf_array_t* array)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_parse_json.c */
extern
int ytf_parse_json
  (const vec_t* string, ytf_t* ytf)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_query.c */
extern
int ytf_query
  (const ytf_t* object, const char* path, ytf_t** result)
  __attribute__ ((warn_unused_result));



#endif