/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _YTF_FUNCTIONS_FUNCTIONS_H_
#define _YTF_FUNCTIONS_FUNCTIONS_H_

/* declared in ./flat_handler.c */
extern
int flat_grammar_process_node
  (
    gpeg_capture_t* capture,
    void* ptr
  )
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_BLOB
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_STRING
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_INT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_FLOAT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_SEPARATOR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_COLON
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_SPACE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_NULL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_COMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_NVPAIR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_YTF
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_BOOL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_OBJECTS
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_NAME
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_NEWLINE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_VALUE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_MULTILINECOMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_OBJECT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_END
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_BLOB
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_STRING
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_INT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_FLOAT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_SEPARATOR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_COLON
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_SPACE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_NULL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_COMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_NVPAIR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_YTF
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_BOOL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_OBJECTS
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_NAME
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_NEWLINE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_VALUE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_MULTILINECOMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_OBJECT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_END
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_BLOB
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_STRING
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_INT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_FLOAT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_SEPARATOR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_COLON
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_SPACE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_NULL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_COMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_NVPAIR
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_YTF
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_BOOL
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_OBJECTS
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_NAME
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_NEWLINE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_VALUE
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_MULTILINECOMMENT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_OBJECT
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./flat_handler_impl.c */
extern
int flat_handle_post_post_END
  (gpeg_capture_t* p, unsigned i, gpeg_capture_t* c, void* a)
  __attribute__ ((warn_unused_result));

/* declared in ./json_handler.c */
extern
int json_grammar_process_node
  (
    gpeg_capture_t* capture,
    void* ptr
  )
  __attribute__ ((warn_unused_result));

/* declared in ./json_parse.c */
extern
ytf_t* json_parse
  (gpeg_capture_t* c)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_encode.c */
extern
void ytf_encode_bit
  (ytf_parse_t* ytf, unsigned bit);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_bit
  (ytf_parse_t* ytf, unsigned* bit);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_bits
  (ytf_parse_t* ytf, unsigned bits, unsigned nbits);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_bits
  (ytf_parse_t* ytf, unsigned* bits, unsigned nbits);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_type
  (ytf_parse_t* ytf, unsigned type);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_type
  (ytf_parse_t* ytf, unsigned* type);

/* declared in ./ytf_encode.c */
extern
void ytf_encode_byte
  (ytf_parse_t* ytf, unsigned char B);

/* declared in ./ytf_encode.c */
extern
void ytf_decode_byte
  (ytf_parse_t* ytf, unsigned char* B);

/* declared in ./ytf_encode_bin.c */
extern
int ytf_encode_bin
  (ytf_t* ytf, vec_t* bin)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_encode_buffer.c */
extern
void ytf_encode_buffer
  (ytf_parse_t* ytf, unsigned char* buf, unsigned size);

/* declared in ./ytf_encode_buffer.c */
extern
void ytf_decode_buffer
  (ytf_parse_t* ytf, unsigned char** buf, unsigned* size);

/* declared in ./ytf_encode_flat.c */
extern
int ytf_encode_flat
  (ytf_t* ytf, vec_t* flat)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_encode_float.c */
extern
void ytf_encode_float
  (ytf_parse_t* ytf, double d);

/* declared in ./ytf_encode_float.c */
extern
void ytf_decode_float
  (ytf_parse_t* ytf, double* d);

/* declared in ./ytf_encode_int.c */
extern
void ytf_encode_int
  (ytf_parse_t* ytf, int64_t n);

/* declared in ./ytf_encode_int.c */
extern
void ytf_decode_int
  (ytf_parse_t* ytf, int64_t* n);

/* declared in ./ytf_encode_json.c */
extern
void ytf_encode_json_string
  (unsigned char* str, unsigned size, vec_t* json);

/* declared in ./ytf_encode_json.c */
extern
void ytf_encode_json
  (ytf_t* ytf, vec_t* json);

/* declared in ./ytf_encode_lv.c */
extern
void ytf_encode_lv
  (ytf_parse_t* ytf, void* buf, unsigned size);

/* declared in ./ytf_encode_lv.c */
extern
void ytf_decode_lv
  (ytf_parse_t* ytf, void* buf, unsigned size);

/* declared in ./ytf_parse_bin.c */
extern
int ytf_parse_bin
  (const vec_t* string, ytf_t* ytf)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_parse_flat.c */
extern
int ytf_parse_flat
  (const vec_t* string, ytf_t* ytf)
  __attribute__ ((warn_unused_result));

/* declared in ./ytf_parse_json.c */
extern
int ytf_parse_json
  (const vec_t* string, ytf_t* ytf)
  __attribute__ ((warn_unused_result));



#endif